### ISSUE TITLE
Could you make it with passwordless authentication 

### ISSUE THREAD

**Issue by shreyasajj** [fdcastel/Proxmox-Automation#7]
The Repo https://github.com/tteck/Proxmox creates LXC with passwordless login. Since I do not run the client with ssh server enabled, it doesnt matter to me if there is a password or not because you must go through proxmox to get to it.

Is this possible to add to your script

**Comment by fdcastel** [comment]
It's not clear to me exactly what you want to change in these scripts, but well written PRs are welcome.
